[package]
name = "completion-notifier"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.95"
clap = { version = "4.5.23", features = ["derive"] }
ctrlc = "3.4.5"
reqwest = { version = "0.12", features = ["json"] }
tokio = { version = "1.42.0", features = ["full"] }
